# -*- coding: utf-8 -*-
"""Summarization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O71Lw95jjCDI0xhjPFnzr1e234-5C4i8
"""

!pip install python-docx pdfplumber

from transformers import pipeline
from PyPDF2 import PdfReader
import pdfplumber
from docx import Document

pdf_path = ""
output_word_path = ""

def extract_text_from_pdf(pdf_path):
    with pdfplumber.open(pdf_path) as pdf:
        full_text = ""
        for page in pdf.pages:
            full_text += page.extract_text()
    return full_text

def summarize_text(text, max_length=500, min_length=100):
    summarizer = pipeline("summarization", model="facebook/bart-large-cnn")
    summarized_text = summarizer(text, max_length=max_length, min_length=min_length, do_sample=False)[0]['summary_text']
    return summarized_text

def save_summary_to_word(summary_text, output_path):
    doc = Document()
    doc.add_heading('Summary', 0)
    doc.add_paragraph(summary_text)
    doc.save(output_path)

full_text = extract_text_from_pdf(pdf_path)

if not full_text.strip():
    raise ValueError("Invalid PDF file!")

if len(full_text) > 1024:
    full_text = full_text[:1024]

summary = summarize_text(full_text)

print(f"Summarized: {summary}")

save_summary_to_word(summary, output_word_path)
print("Done!")